# CI de Nível 01 - Disparo manual a partir de 1 clique

# nome que vai aparecer la nas opções de pipe
name: "Execução Manual"

# regras de disparo da execucao (triggers/gatilhos)
# gatilho de exec manual = workflow_dispatch

on:
  workflow_dispatch:

jobs:
  inspection:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Padronizacao de codigo (Lint)
        run: yarn lint

  # descricao do job
  e2e-tests:
    # maquina que o job vai executar
    runs-on: ["ubuntu-latest"]
    needs: [inspection]
    timeout-minutes: 3

    # passo a passo das acoes do job
    steps:
      - uses: actions/checkout@v4

      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: lts/*

      - name: Instalando cypress
        run: npm install
        timeout-minutes: 3

      - name: Check Cypress version
        run: npx cypress --version
        timeout-minutes: 3

      - name: Executando E2E tests
        run: npx cypress run --browser=electron
        timeout-minutes: 10

        # disponibilizando relatorio (artefato)
      # passed, failed, cancelled
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./mochawesome-report

      